function new_set(previous_set)

fig1 = figure(1);
set(1,'resize','On','numbertitle','Off',...
    'windowstyle','normal',...
    'Units','Norm', ...
    'Pos',[0 0 1 1]);

if previous_set > 0
    h = uicontrol('Style', 'text', 'String','Please wait ...', 'FontSize', 25, ...
    'Units','Norm', ...
    'Position', [ 0 0.55 1 0.05 ]);
else
    h = uicontrol('Style', 'text', 'String','Actual experiment will start soon ...', 'FontSize', 25, ...
    'Units','Norm', ...
    'Position', [ 0 0.55 1 0.05 ]);
end

end